version: '3.3'
services:
  filebeat:
    build:
      context: filebeat/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: filebeat
    user: root
    command:
        # Log to stderr.
      #- -e
        # Disable config file permissions checks. Allows mounting
        # 'config/metricbeat.yml' even if it's not owned by root.
        # see: https://www.elastic.co/guide/en/beats/libbeat/current/config-file-permissions.html
      - --strict.perms=false
        # Mount point of the host’s filesystem. Required to monitor the host
        # from within a container.
      # - --system.hostfs=/hostfs
    volumes:
      - type: bind
        source: ./filebeat/config/filebeat.yml
        target: /usr/share/filebeat/config/filebeat.yml
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /host_docker/docker.sock
        read_only: true
      - type: bind
        source: /var/lib/docker
        target: /host_docker/var/lib/docker
        read_only: true
      # - type: bind
      #   source: /home/ec2-user/.pm2/logs/ts-node-out.log
      #   target: /usr/share/filebeat/api-log/ts-node-out.log
      #   read_only: true
      # - type: bind
      #   source: /var/log/qmrd/qmr-app-out.log
      #   target: /usr/share/filebeat/sync-log/qmr-app-out.log
      #   read_only: true
      # - type: bind
      #   source: /var/log/qmrd/download-out.log
      #   target: /usr/share/filebeat/download-log/download-out.log
      #   read_only: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    network_mode: bridge
    deploy:
      mode: global