version: '3.3'
services:
  es01:
    container_name: es01
    image: 'elasticsearch:$ELASTIC_VERSION'
    environment:
      - node.name=es01
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=es02
      - cluster.name=es-docker-cluster
      - 'cluster.initial_master_nodes=es01,es02'
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - cluster.routing.allocation.disk.threshold_enabled=false
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.enabled=$ELASTIC_SECURITY
    volumes:
      - 'data01:/usr/share/elasticsearch/data'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9200:9200'
      - '9300:9300'
    stdin_open: true
    tty: true
    networks:
      - elastic-network
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '50'
  es02:
    container_name: es02
    image: 'elasticsearch:$ELASTIC_VERSION'
    environment:
      - node.name=es02
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=es01
      - cluster.name=es-docker-cluster
      - 'cluster.initial_master_nodes=es01,es02'
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - cluster.routing.allocation.disk.threshold_enabled=false
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.enabled=$ELASTIC_SECURITY
    volumes:
      - 'data02:/usr/share/elasticsearch/data'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    stdin_open: true
    tty: true
    networks:
      - elastic-network
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '50'
  kibana:
    container_name: kibana
    image: 'kibana:7.11.2'
    environment:
      - ELASTICSEARCH_URL: 'http://es01:9200'
      - ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200"]'
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '5601:5601'
    stdin_open: true
    tty: true
    networks:
      - elastic-network
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '50'
volumes:
  data01:
    driver: local
  data02:
    driver: local
networks:
  elastic-network:
    driver: bridge
