filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/log/*.log
  encoding: utf-8

output.logstash:
  hosts: ["54.95.67.134:5044"]

processors:
  - add_docker_metadata:
      host: "unix:///host_docker/docker.sock"